#ifndef TOKEN_H
#define TOKEN_H


/*
 * Includes
*/
#include <stddef.h> // size_t


/*
 * Enums
*/
typedef enum e_token_type {
	// Specials
	TOKEN_EOF,
	TOKEN_ERROR,

	// Identifiers
	TOKEN_IDENTIFIER,

	// Literals
	TOKEN_LIT_INT,
	TOKEN_LIT_FLOAT,
	TOKEN_LIT_CHAR,
	TOKEN_LIT_STRING,

	// Keywords
	TOKEN_KW_AUTO,
	TOKEN_KW_BREAK,
	TOKEN_KW_CASE,
	TOKEN_KW_CHAR,
	TOKEN_KW_CONST,
	TOKEN_KW_CONTINUE,
	TOKEN_KW_DEFAULT,
	TOKEN_KW_DO,
	TOKEN_KW_DOUBLE,
	TOKEN_KW_ELSE,
	TOKEN_KW_ENUM,
	TOKEN_KW_EXTERN,
	TOKEN_KW_FLOAT,
	TOKEN_KW_FOR,
	TOKEN_KW_GOTO,
	TOKEN_KW_IF,
	TOKEN_KW_INT,
	TOKEN_KW_LONG,
	TOKEN_KW_REGISTER,
	TOKEN_KW_RETURN,
	TOKEN_KW_SHORT,
	TOKEN_KW_SIGNED,
	TOKEN_KW_SIZEOF,
	TOKEN_KW_STATIC,
	TOKEN_KW_STRUCT,
	TOKEN_KW_SWITCH,
	TOKEN_KW_TYPEDEF,
	TOKEN_KW_UNION,
	TOKEN_KW_UNSIGNED,
	TOKEN_KW_VOID,
	TOKEN_KW_VOLATILE,
	TOKEN_KW_WHILE,

	// Operators
	TOKEN_OP_LSHIFT_ASSIGN,
	TOKEN_OP_RSHIFT_ASSIGN,
	TOKEN_OP_ARROW,
	TOKEN_OP_INCREMENT,
	TOKEN_OP_DECREMENT,
	TOKEN_OP_LEQ,
	TOKEN_OP_GEQ,
	TOKEN_OP_EQ,
	TOKEN_OP_NEQ,
	TOKEN_OP_LOGICAL_AND,
	TOKEN_OP_LOGICAL_OR,
	TOKEN_OP_LSHIFT,
	TOKEN_OP_RSHIFT,
	TOKEN_OP_ADD_ASSIGN,
	TOKEN_OP_SUB_ASSIGN,
	TOKEN_OP_MUL_ASSIGN,
	TOKEN_OP_DIV_ASSIGN,
	TOKEN_OP_AND_ASSIGN,
	TOKEN_OP_OR_ASSIGN,
	TOKEN_OP_INV_ASSIGN,
	TOKEN_OP_XOR_ASSIGN,
	TOKEN_OP_ADD,
	TOKEN_OP_SUB,
	TOKEN_OP_MUL,
	TOKEN_OP_DIV,
	TOKEN_OP_MOD,
	TOKEN_OP_LESS,
	TOKEN_OP_GREATER,
	TOKEN_OP_NOT,
	TOKEN_OP_AND,
	TOKEN_OP_OR,
	TOKEN_OP_INV,
	TOKEN_OP_XOR,
	TOKEN_OP_ASSIGN,
	TOKEN_OP_QUESTION,
	TOKEN_OP_COLON,

	// Punctuators
	TOKEN_PUNC_ELLIPSIS,
	TOKEN_PUNC_LPAREN,
	TOKEN_PUNC_RPAREN,
	TOKEN_PUNC_LBRACE,
	TOKEN_PUNC_RBRACE,
	TOKEN_PUNC_LBRACKET,
	TOKEN_PUNC_RBRACKET,
	TOKEN_PUNC_SEMICOLON,
	TOKEN_PUNC_COMMA,
	TOKEN_PUNC_DOT
} t_token_type;


/*
 * Structures
*/
typedef struct s_token {
	t_token_type type;
	const char *start;
	size_t len;
	size_t line;
	size_t col;
} t_token;


typedef struct s_token_list {
	t_token token;
	struct s_token_list *next;
} t_token_list;


/*
 * Prototypes
*/
// token_list.c
void token_list_init(t_token_list *lst);
int token_list_push(t_token_list **lst, t_token tok);
void token_list_free(t_token_list **lst);

// utils.c
void print_token_list(t_token_list *tok_lst);


#endif
